RSSREADER/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rss.urls'))
]

rss/urls.py
from django.urls import path, include
from . import views
app_name = 'rss'
urlpatterns = [

    path('rss/', views.index, name="index"),
    path('info/', views.Score, name="info"),
    path('about/', views.about, name="about"),
    path('scorecard/', views.scorecard, name="scorecard"),
    path('schedule/', views.schedule, name="schedule"),
    path('match_details/', views.match_details, name="match_details"),
    path('batting_ranking/', views.batting_ranking, name="batting_ranking"),
    path('bowling_ranking/', views.bowling_ranking, name="bowling_ranking"),
    path('all_rounder_ranking/', views.all_rounder_ranking, name="all_rounder_ranking"),
    path('team_ranking/', views.team_ranking, name="team_ranking"),


]

rss/models.py
from django.db import models

# Create your models here.

rss/views.py
import requests
from django.shortcuts import render
import scrapy
from requests_html import HTMLSession
from django.http import HttpResponse
import feedparser
from bs4 import BeautifulSoup
import json


def index(request):
    if request.method == 'POST':
        link = "https://www.espncricinfo.com/scores"
        data = live_score(link)
        print(data)
        url = 'http://static.cricinfo.com/rss/livescores.xml'
        feed = feedparser.parse(url)
        return HttpResponse(json.dumps(data))
    else:
        link = "https://www.espncricinfo.com/scores"
        data = live_score(link)
        url = 'http://static.cricinfo.com/rss/livescores.xml'
        feed = feedparser.parse(url)
        return render(request, 'reader.html', {"feed": feed, "data": data})


def live_score(link):
    session = requests.Session()
    content = session.get(link, verify=False).content
    soup = BeautifulSoup(content, "html.parser")

    post = soup.find("div", {"class": "scoreCollection"})
    collection = post.find("div", {"class": "scoreCollection__content"})
    all_events = collection.findAll("div", {"class": "cscore"})
    data = []
    for rec in all_events:
        dic = {}
        teams = []
        cscore_link = rec.find("div", {"class": "cscore_link cscore_link--button"})
        dic['title'] = cscore_link.find("div", {"class": "cscore_info-overview"}).text
        dic['date'] = cscore_link.find("span", {"class": "cscore_date"}).text
        url = cscore_link.find("a", {"class": "cscore_details"})
        if url:
            dic['urls'] = (url['href'])
        events = cscore_link.find("a", {"class": "cscore_details"}).find("ul")
        dic['note'] = cscore_link.find("span", {"class": "cscore_notes_game"}).text

        for i in events.find_all("li", {"class": "cscore_item"}):
            team = {}
            image = i.find("img", {"class": "cscore_image"})
            if image:
                team['image'] = (image['data-src'])
            # team['image'] = i.find("img", {"class": "cscore_image"})
            team['team_name'] = i.find("span", {"class": "cscore_name"}).text
            score = i.find("div", {"class": "cscore_score"})
            if score:
                team['score'] = i.find("div", {"class": "cscore_score"}).text
            over = i.find("span", {"class": "cscore_overs"})
            if over:
                team['over'] = i.find("span", {"class": "cscore_overs"}).text

            teams.append(team)
        dic['teams'] = teams
        data.append(dic)

    return {"data": data}


def Score(request):
    session = HTMLSession()
    link = request.POST.get("link")

    date = request.POST.get("date")
    teams = request.POST.get("teams")
    title = request.POST.get("title")
    note = request.POST.get("note")

    if teams:
        re = teams.replace("'", "\"")
        teams_s = json.loads(re)

    data = scrape(link)

    return render(request, 'Scores.html', {"data": data , "teams_s": teams_s, "date": date, "title": title, "note": note})


def scrape(link):
    session = requests.Session()

    content = session.get(link, verify=False).content
    soup = BeautifulSoup(content, "html.parser")
    page_title = soup.find("title").text
    post = soup.find("div", {"class": "cscore_link"})
    pre_coummatry = soup.find("div", {"class": ["commentary-item pre"]})
    pre_com = []
    if pre_coummatry:
        pre = pre_coummatry.find_all("p", {"class": "comment"})
        for i in pre:
            d = i.text
            pre_com.append(d)
    man_of_the_match = soup.find("div", {"class": "gp__cricket__player-match"})
    if man_of_the_match:
        man_of_the_match_jersey = man_of_the_match.find("a", {"class": "headshot-jersey-sm"})
        man_of_the_match_player_name = man_of_the_match.find("a", {"class": "gp__cricket__player-match__player__detail__link"}).text
        title_of_man_of_the_match = man_of_the_match.find("div", {"class": "gp__cricket__player-match__title"}).text
    else:
        man_of_the_match_jersey =''
        man_of_the_match_player_name =''
        title_of_man_of_the_match =''

    link = post.find("span", {"class":"cscore_date"}).text
    strt = post.find("span", {"class": "cscore_time"})
    status = ''
    if strt:
        status = post.find("span", {"class":"cscore_time"}).text
    match_no = post.find("div", {"class": "cscore_info-overview"}).text
    toss = soup.find("div", {"class": "cscore_commentary"})
    toss_win = ''
    if toss:
        toss_in = soup.find("div", {"class": "cscore_commentary"})
        toss_win = toss_in.find("span", {"class": "cscore_notes_game"}).text
    details = post.find("div", {"class":"cscore_details"}).find("ul")
    score = details.find_all("div",{"class": "cscore_score"})
    score_details =[]
    over_details = []
    for i in score:
        over_1 = i.find("span", {"class":"cscore_overs"})
        over_details.append(over_1)
    team_name = []
    flag = []
    for litag in details.find_all('li'):
        flag = litag.find("img", {"class": "cscore_image"})
        score_card = litag.find("div",{"class": "cscore_score"}).text
        score_details.append(score_card)
        team_name1 = litag.find("span", {"class": "cscore_name--long"}).text
        team_name.append(team_name1)
    info_summary = soup.find("div", {"class": "col-large"})
    content_summary = info_summary.find("div", {"class":"content"})
    over = content_summary.find("div",{"class":"time-stamp"})
    description = content_summary.find("div",{"class":"description"})
    for i in content_summary.find_all("p", {"class": "comment"}):
        print(i)
    post_summary = content_summary.find("p", {"class":"comment"})

    #nav details
    link_scorecard = []
    link_game = []
    nav_div = soup.find("nav", {"class":"game-package-nav"}).find("ul")
    for i in nav_div.find_all("li",{"class": "sub"}):
        #Live
        game = i.find("a", {"class":"game"})
        link_text = i.find("span", {"class": "link-text"}).text
        if game:
            link_text = 'live'
            link_game1 = (game["href"])
            link_game.append(link_game1)

        else:
            link_text = ''
        #scorecard
        scorecard_details = i.find("a", {"class": "scorecard"})

        if scorecard_details:
            link_text_scorecard = 'scorecard'
            link_scorecard1 = (scorecard_details["href"])
            link_scorecard.append(link_scorecard1)
        else:
            link_text_scorecard = ''



    data_table = []
    batmans = []
    bowlers = []
    current_details = []
    over_detail = []
    article = soup.find("article", {"class": ["sub-module", "scorecard"]})
    tables = article.find('table')
    if tables:
        table_body = tables.find_all('tbody')
        for i in table_body:
            rows = i.find_all('tr')
            for row in rows:
                cols = row.find_all('td')

                cols = [ele.text.strip() for ele in cols]
                data_table.append([ele for ele in cols if ele])


        count = 0
        for rec in data_table:
            if count < 2:
                batmans.append(rec)
                count = count + 1



        count_bowlers = 0
        for rec in data_table:
            count_bowlers = count_bowlers + 1
            if count_bowlers >= 3:
                if count_bowlers < 5:
                    bowlers.append(rec)



        count_current = 0
        for rec in data_table:
            count_current = count_current + 1
            if count_current == 5:
                current_details.append(rec)

            if count_current == 6:
                over_detail.append(rec)


    summary = soup.find_all("article", {"class": ["sub-module", "match-commentary"]})[3:4]
    if summary:
        for rec in summary:
            post_summary1 = rec.find_all("div", {"class":"commentary-item"})

            summary_post = []
            for i in post_summary1:
                summary_post.append(i.text)
    else:
        summary_post = ''

    inning = article.find_all("div", {"class": "scorecard-section"})
    data = {"date": link,"page_title":page_title,"status":status, "match_no": match_no, "toss_win": toss_win, "team_name": team_name, "flag": flag, "post_summary":post_summary,
            "data_table": data_table,"batmans":batmans,"bowlers":bowlers, "link_text":link_text, "link_game":link_game, "link_text_scorecard":link_text_scorecard,"link_scorecard":link_scorecard,
            "score_details":score_details,"over_details":over_details,"summary_post":summary_post, "current_details":current_details,"over_detail":over_detail,"man_of_the_match_jersey":man_of_the_match_jersey,
            "man_of_the_match_player_name":man_of_the_match_player_name,"pre_com":pre_com, "title_of_man_of_the_match":title_of_man_of_the_match }

    return data


def scorecard(request):
    link = request.POST.get("link")
    rec1 = request.POST.get("date")
    teams_s = request.POST.get("teams")
    title = request.POST.get("title")
    note = request.POST.get("note")
    page_title = request.POST.get("page_title")
    if teams_s:
        re = teams_s.replace("'", "\"")
        teams = json.loads(re)
    else:
        teams = {}

    data = score_details(link)
    return render(request, 'scorecard.html',{"data": data, "page_title":page_title, "teams": teams, "title": title, "note": note, "date": rec1})


def score_details(link):
    session = requests.Session()
    content = session.get(link, verify=False).content
    soup = BeautifulSoup(content, "html.parser")
    article = soup.find("article", {"class": ["sub-module scorecard"]})
    batmans_section = article.find("div", {"class": ["scorecard-section batsmen"]})
    flex_row = batmans_section.find_all("div", {"class": ["flex-row"]})

    # For Batmans
    batsmen_first = []
    yet = []
    totals1 = []
    for rec in flex_row:
        dic = {}
        runs = []
        wrap_batsmen = rec.find("div", {"class": ["wrap batsmen"]})

rss/templates/Scores.html
{% extends 'base.html' %}
{% load my_filters %}
{% block head %}
    <title>{{ data.page_title }}</title>
{% endblock %}
{% block styleBlock %}
    <style>
        .heading {
            margin-left: 20%;
            font-size: 200%;
            background: #314569;
            width: 60%;
            text-align: center;
            color: white;
        }

        .details {
            width: 60%;
            border: 1px solid #ccc !important;
            margin-left: 20%;
            margin-bottom: 2%;
            border-radius: 4%;
        }

        p, h4 {
            font-family: "Times New Roman", Times, serif;
        }

        #customers {
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            border-collapse: collapse;
            width: 80%;
            margin-left: 10%;
        }

        #customers td, #customers th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        #customers tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        #customers tr:hover {
            background-color: #ddd;
        }

        #customers th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #314569;
            color: white;
        }
    </style>
{% endblock %}

{% block body %}
    {#    <h4>{{ info }}</h4>#}
    {#    <h4>{{ team.0.full_text }}{{ score.0.full_text }}</h4>#}
    {#    <h4>{{ team.1.full_text }}{{ score.1.full_text }}</h4>#}

    {#    <h4>{{ record }}</h4>#}
    {#    <h4>{{ table }}</h4>#}
    {#    <h4>{{ articles }}</h4>#}
    {#    <h4>{{ team_name }}</h4>#}

    <div class="">
        <div>
            <p class="heading">Match</p>
        </div>
    </div>
    <div class="live_score">
        <div class="details">
            {% if data.status %}
                <h4 style="color: red; margin-left: 5%; ">{{ data.status }}</h4>
            {% else %}
                <h4 style="color: red; margin-left: 5%; ">{{ date }}</h4>
            {% endif %}
            <p style=" margin-left: 5%;">{{ data.match_no }}</p>
            {% if data.toss_win %}
                <p style=" margin-left: 5%;">{{ data.toss_win }}</p>
            {% else %}
                <p style=" margin-left: 5%;">{{ note }}</p>
            {% endif %}
            {% if data.title_of_man_of_the_match and data.man_of_the_match_player_name %}
                <p style="position: absolute;margin-left: 45%;  margin-top: -9%;color: #de7870;">{{ data.title_of_man_of_the_match }} </p>
                <p style="position: absolute; margin-left: 42%;margin-top: -7%;">{{ data.man_of_the_match_player_name|upfirstletter:"  " }} </p>
            {% endif %}
            {% for i in teams_s %}
                <img src="{{ i.image }}" style="position: absolute; margin-left: 1%;     ">

                <h4 style="margin-left: 9%; margin-top: 2%;">{{ i.team_name }}</h4>
                {#                        <p style="position: absolute;margin-left: 20%; margin-top: -3%;">{{ i.score }}</p>#}
                {#                        <h4>{{ i.over }}</h4>#}
            {% endfor %}
            {#             {% for i in data.team_name %}#}
            {#                <h4 style="margin-left: 9%; margin-top: 2%;">{{ i }}</h4>#}
            {#             {% endfor %}#}
            {% for i in data.score_details %}
                {% if forloop.counter == 1 %}
                    <p style="position: absolute; margin-top: -6%; margin-left: 20%;">{{ i }}</p>
                {% else %}
                    <p style="position: absolute; margin-top: -3%; margin-left: 20%;">{{ i }}</p>
                {% endif %}
            {% endfor %}
            <form id="myForm" action="{% url 'rss:scorecard' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for rec in data.link_scorecard %}
                    <a id='tc_review-{{ forloop.counter }}' class="fa-times1"
                       style="margin-left: 5%; color: red; content: none; margin-left: 80%;" href="javascript:void(0)">Scorecard</a>

                    <input type="hidden" id="link_id" name="link1" value="https://www.espncricinfo.com{{ rec }}">
                    <input type="hidden" id="link_{{ forloop.counter }}" name="link"
                           value="https://www.espncricinfo.com{{ rec }}">
                {% endfor %}
                <input type="hidden" id="date_id" name="date" value="{{ date }}">
                <input type="hidden" id="date_{{ forloop.counter }}" name="date1" value="{{ date }}">
                <input type="hidden" id="page_title_id" name="page_title" value="{{ data.page_title }}">
                <input type="hidden" id="page_title_{{ forloop.counter }}" name="page_title1"
                       value="{{ data.page_title }}">

                <input type="hidden" id="teams_id" name="teams" value="{{ teams_s }}">
                <input type="hidden" id="teams_{{ forloop.counter }}" name="teams1" value="{{ teams_s }}">

                <input type="hidden" id="title_id" name="title" value="{{ data.match_no }}">
                <input type="hidden" id="title_{{ forloop.counter }}" name="title1" value="{{ data.match_no }}">

                <input type="hidden" id="note_id" name="note" value="{{ note }}">
                <input type="hidden" id="note_{{ forloop.counter }}" name="note1" value="{{ note }}">
            </form>
        </div>

        <div class="details">
            {% if not data.score_details.0 == '' %}
                <div class="batmen" style="margin-top: 3%; margin-bottom: 5%;">
                    {% if data.batmans %}
                        <h4 style="color: red; margin-left: 5%">Currently Bating</h4>
                        <table id="customers">
                            <tr>
                                <th>BATSMEN</th>
                                <th>R</th>
                                <th>B</th>
                                <th>4s</th>
                                <th>6s</th>
                                <th>SR</th>
                                <th>LAST OVS</th>
                                <th>MAT</th>
                                <th>RUNS</th>
                                <th>HS</th>
                                <th>AVE</th>
                            </tr>
                            {% for i in data.batmans %}
                                <tr>
                                    {% for rec in i %}
                                        {% if forloop.counter == 1 %}
                                            <td>{{ rec|truncatechars:13 }}</td>
                                        {% elif  forloop.counter == 7 %}

                                        {% else %}
                                            <td>{{ rec }}</td>
                                        {% endif %}

                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </table>
                    {% endif %}
                </div>
                <div class="bowling" style="margin-top: 3%; margin-bottom: 5%;">
                    {% if data.bowlers %}
                        <h4 style="color: red; margin-left: 5%">Currently Bowling</h4>
                        <table id="customers">
                            <tr>
                                <th>BOWLERS</th>
                                <th>O</th>
                                <th>M</th>
                                <th>R</th>
                                <th>W</th>
                                <th>ECON</th>
                                <th>0s</th>
                                <th>4s</th>
                                <th>6s</th>
                                <th>MAT</th>
                                <th>WKTS</th>
                                <th>BBI</th>
                                <th>AVE</th>
                            </tr>
                            {% for i in data.bowlers %}
                                <tr>
                                    {% for rec in i %}
                                        {% if forloop.counter == 1 %}
                                            <td>{{ rec|truncatechars:13 }}</td>
                                        {% elif  forloop.counter == 10 %}

                                        {% else %}
                                            <td>{{ rec }}</td>
                                        {% endif %}

                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </table>
                    {% endif %}
                </div>
            {% endif %}
            <div>
                <h4 style="margin-left: 5%; color: red;">Summary</h4>
                {% for i in data.pre_com %}
                    <p style="margin-left: 9%">{{ i }}</p><br>
                {% endfor %}
                {% if data.score_details %}
                    {#                        <h4 style="color: red; margin-left: 5%">Details</h4>#}
                    {% for i in data.current_details %}
                        {% for rec in i %}
                            <p style="margin-left: 9%">{{ rec }}</p>
                        {% endfor %}
                    {% endfor %}
                {% endif %}
                {% if data.over_detail %}
                    {% for i in data.over_detail %}
                        {% for rec in i %}
                            <p style="margin-left: 9%">{{ rec }}</p>
                        {% endfor %}
                    {% endfor %}
                    {#                        <h4 style="margin-left: 5%; color: red;">Last Overs Details</h4>#}
                    {% for i in data.summary_post %}
                        <p style="margin-left: 9%">{{ i }}</p>
                    {% endfor %}

                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block ScriptBlock %}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            $(document).on('click', '.fa-times1', function (e) {
                var image_id = event.srcElement.id.split('-')[1];
                var link = $("#link_" + image_id).val();
                var date = $("#date_id").val();
                var teams = $("#teams_id").val();
                var title = $("#title_id").val();
                var note = $("#note_id").val();
                var page_title_id = $("#page_title_id").val();
                $("#link_id").val(link);
                $("#date_id").val(date);
                $("#teams_id").val(teams);
                $("#title_id").val(title);
                $("#note_id").val(note);
                $("#page_title_id").val(page_title_id);

                document.getElementById('myForm').submit();
            });
        });


        {#var append_increment = 0;#}
        {#setInterval(function () {#}
        {#    $.ajax({#}
        {#        type: "GET",#}
        {#        url: {% url 'rss:info' %},  // URL to your view that serves new info#}
        {#        data: {'append_increment': append_increment}#}
        {#    })#}
        {#        .done(function (response) {#}
        {#            $('#_appendHere').append(response);#}
        {#            append_increment += 10;#}
        {#        });#}
        {#, 10000)#}

        {#window.setTimeout(function () {#}
        {#    location.href = "/rss/";#}
        {#, 5000); // refresh/redirect after 5 seconds.#}

    </script>
{% endblock %}

rss/templates/about.html
{% extends "base.html" %}
{% block head %}
    <title>About</title>
{% endblock %}
{% block styleBlock %}
    <style>
        .heading {
            margin-left: 25%;
            font-size: 200%;
            background: #314569;
            width: 50%;
            text-align: center;
            color: white;
        }

        .details {
            width: 60%;
            border: 1px solid #ccc !important;
            margin-left: 20%;
            margin-bottom: 2%;
            border-radius: 4%;
        }

        p {
            font-family: "Times New Roman", Times, serif;
        }
    </style>
{% endblock %}
{% block body %}
    <div class="">
        <div>
            <p class="heading">About</p>
        </div>
    </div>
    <div class="details">
        <h4 style="margin-left: 5%; color: red;">About</h4>
        <p style="margin-left: 5%; font-family:;">Live Cricket Score(LCS) is the world's leading cricket website and
            among the top single-sport websites in the world.

            Founded in 2019, LCScricinfo's content includes news, live ball-by-ball coverage of one-day international
            matches and features written by some of the world's best cricketers and cricket writers. The site also
            includes in-depth statistics on every one of the 3000 international and 50,000 first-class cricketers to
            have played the game.

            Now a wholly owned subsidiary of Lsc Inc., the world's leading multimedia sports entertainment company,
            LCScricinfo is available to cricket fans through the online media and on a host of mobile platforms and
            handheld devices.

            LCScricinfo has a thriving user community and reaches over 0 million users every month.


            In 2019 Cricinfo became a part of LCS | Press Release | Editor's Comment

        </p>
    </div>
{% endblock %}

rss/templates/schedule_details.html
{% extends "base.html" %}
{% block styleBlock %}
    <style>
        .heading {
            margin-left: 25%;
            font-size: 200%;
            background: #314569;
            width: 50%;
            text-align: center;
            color: white;
        }

        .details {
            width: 60%;
            border: 1px solid #ccc !important;
            margin-left: 20%;
            margin-bottom: 2%;
            border-radius: 4%;
        }
    </style>
{% endblock %}

{% block body %}
    <div class="">
        <div>
            <p class="heading">Series / Tournaments</p>
        </div>
    </div>
    <div class="details">
        {% for i in data.final %}
            <h4 style="color: red; margin-left: 5%;">International Tournaments</h4>
            {% for r in i %}
                <form id="myForm" action="{% url 'rss:match_details' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <a href="javascript:void(0)" id='tc_review-{{ forloop.parentloop.counter }}-{{ forloop.counter }}'
                       class="fa-times1"
                       style="text-decoration: none !important; margin-left: 8%; color: #314569;">{{ forloop.counter }}. {{ r.match }}</a><br>
                    <input type="hidden" id="link_{{ forloop.parentloop.counter }}-{{ forloop.counter }}"
                           name="link_{{ forloop.parentloop.counter }}-{{ forloop.counter }}"
                           value="{{ r.match_link }}">
                    <input type="hidden" id="link_id" name="link" value="{{ r.match_link }}">
                </form>
            {% endfor %}
        {% endfor %}
    </div>
{% endblock %}
{% block ScriptBlock %}

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

    <script>
        $(document).ready(function () {

            $(document).on('click', '.fa-times1', function (e) {
                var image_id = event.srcElement.id.split('-')[1];
                var image_id1 = event.srcElement.id.split('-')[2];
                var link = $("#link_" + image_id + '-' + image_id1).val();
                $("#link_id").val(link);
                document.getElementById('myForm').submit();
                {#$.post('/info/', {#}
                {#    'link': link,#}
                {#    'csrfmiddlewaretoken': $("input[name=csrfmiddlewaretoken]").val(),#}
                {#, function (data) {#}
                {#    var response = data['message'];#}
                {#);#}

            });
        });
    </script>
{% endblock %}